# Generated by Django 4.2.1 on 2023-05-28 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_guild_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='guild',
            name='user_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='updated_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
