version: '3.8'

services:
    server:
        build: ./server_express
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        # volumes:
        #     - media-data:/site-backend/media
        #     - static-data:/site-backend/static
        depends_on:
            - database
        ports:
            - "8000:8000"
        # env_file:
        #     - .env

    database:
        image: postgres:latest
        container_name: postgres
        volumes:
            - postgres-db-data:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=root
          - POSTGRES_DB=MAIN
          - PGDATA=/var/lib/postgresql/data

volumes:
    postgres-db-data:
        name: postgres-db-data
    # static-data:
    #     name: static-data
    # media-data:
    #     name: media-data

